apiVersion: apps/v1
kind: Deployment
metadata:
    name: analytxdeployment
spec:
  replicas: 1
  minReadySeconds: 45
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 1
         maxSurge: 1
  selector:
    matchLabels:
            app: analytxapp
  template:
     metadata:
         name: analytxpod
         labels:
            app: analytxapp
     spec:
       containers:
           - name: analytxcont
             image: solitx/analytx:1
             resources:
              requests:
                   cpu: 2000m
                   memory: 2Gi
              limits:
                   cpu: 3000m
                   memory: 3Gi
             volumeMounts:
              - mountPath: "/usr/local/tomcat/logs"
                name: my-volume
       volumes:
        - name: my-volume
          persistentVolumeClaim: 
              claimName: analytxpvc          
       imagePullSecrets:
             - name: regcredsolitx
       tolerations:
           - key: node-role.kubernetes.io/master
             operator: Exists
             effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
    name: analytxservice
spec:
  type: NodePort
  selector:
       app: analytxapp
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30000

---

apiVersion: autoscaling/v2

kind: HorizontalPodAutoscaler

metadata:

  name: analytx-hpa

spec:

  scaleTargetRef:

    apiVersion: apps/v1

    kind: Deployment

    name: analytxdeployment

  minReplicas: 1

  maxReplicas: 3 

  metrics:

    - type: Resource

      resource:

        name: memory

        target:

          type: Utilization

          averageUtilization: 5
