apiVersion: v1
kind: Pod
metadata:
  name: multicontpod
  labels:
     app: mff
spec:
  containers:
  - name: zull
    image: nutan69/mffzull
    ports:
     - containerPort: 5055
  - name: login
    image: nutan69/mfflogin
    ports:
     - containerPort: 5052
  - name: users
    image: nutan69/mffusers
    ports:
     - containerPort: 7181
  - name: branch
    image: nutan69/mffbranch
    ports:
     - containerPort: 4003
  - name: portfolio
    image: nutan69/mffportfolio
    ports:
     - containerPort: 4004
  - name: profile
    image: nutan69/mffprofile
    ports:
     - containerPort: 4001
  - name: solitx
    image: nutan69/mffsolitx
    ports:
     - containerPort: 4005
  - name: workflow
    image: nutan69/mffworkflow
    ports:
     - containerPort: 4002
  - name: zookeeper
    image: nutan69/mffzookeeper
    ports:
     - containerPort: 2181
  - name: kafka
    image: nutan69/mffkafka
    ports:
     - containerPort: 9092
  tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
